services:
  redis:
    image: redis:alpine
    restart: always

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ai-interview-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - KRUTRIM_API_KEY=${KRUTRIM_API_KEY}
    depends_on:
      - redis
      - rabbitmq
    restart: always

  worker:
    image: ai-interview-backend
    command: python backend/worker.py
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - KRUTRIM_API_KEY=${KRUTRIM_API_KEY}
    depends_on:
      - fastapi
    restart: always

volumes:
